name: Enclave
main: com.bradenn.dev.enclave.Main
version: 1.4.2
author: bradencn
api-version: 1.17
website: bradenn.com
description: Own land and have a good time.
commands:
  enclave:
    description: Interact with enclaves.
    aliases: e
    usage: /enclave [command] [args]
  enclaveadmin:
    description: Interact with enclaves, but in an admin-like way.
    aliases: ea
    usage: /enclaveadmin [command] [args]
permissions:
  enclave.*:
    default: false
  enclave.override:
    default: op