name: Enclave
main: com.bradenn.dev.enclave.Main
version: 1.3.2
author: bradencn
api-version: 1.16
website: bradenn.com
description: Own land and have a good time. (for opoq)
commands:
  enclave:
    description: Interact with enclaves
    aliases: e
    usage: /enclave [command] <?attribute>
  enclaveadmin:
    description: Interact with enclaves, but in an admin way
    aliases: ea
    usage: /enclaveadmin args0 args1
permissions:
  enclave.*:
    default: false
  enclave.override:
    default: op