name: Enclave
main: com.bradenn.dev.enclave.Main
version: 1.5.4
author: bradencn
api-version: 1.18
website: bradenn.com
description: Own land and have a good time.
softdepend: ["PlaceholderAPI"]
commands:
  enclave:
    description: Interact with enclaves.
    aliases: e
    usage: /e [command] [args]
  enclaveadmin:
    description: Interact with enclaves, but with an iron fist.
    permission: enclave.admin
    aliases: ea
    usage: /ea [command] [args]
permissions:
  enclave.command:
    description: Basic access to all non-admin enclave commands.
    default: true
  enclave.admin:
    description: Access to overriding all enclave commands and permissions.
    default: op
  enclave.admin.interact:
    description: Access to overriding all enclave commands and permissions.
    default: op